name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  buildConfiguration: 'Release' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0
    - name: Build
      run: |
          dotnet build --configuration $buildConfiguration
          dotnet test dotnetcore-tests --configuration $buildConfiguration --logger trx
          dotnet publish --configuration $buildConfiguration --output out
    - name: Test Report
      uses: zyborg/dotnet-tests-report@v1.0.0
      with:
        project_path: "**/*.trx"
        report_name: my_project_tests
        report_title: My Project Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    
