name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  buildConfiguration: 'Release' 
  SERVICE_NAME: sample-dotnet-app
  ENV: dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Build code
      run: |
          dotnet build --configuration $buildConfiguration
    - name: Test code
      run: |
          dotnet add dotnetcore-tests package JunitXml.TestLogger --version 2.1.78
          dotnet test dotnetcore-tests --configuration $buildConfiguration --test-adapter-path:. --logger:junit
          dotnet publish --configuration $buildConfiguration --output out
    - name: Publish Test Report
      uses: zyborg/dotnet-tests-report@v1.0.0
      with:
        project_path: "**/*.trx"
        report_name: Unit_Tests
        report_title: My Project Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/my-organization/${{ env.SERVICE_NAME }}:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/${{ env.SERVICE_NAME }}:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
    
    
