name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  buildConfiguration: 'Release' 
  GITHUB_SHA: ${{ github.sha }}
  SERVICE_NAME: sample-dotnet-app
  REGISTRY_HOSTNAME: ecr
  ENV: dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Build
      run: |
          dotnet build --configuration $buildConfiguration
          dotnet add package JUnitTestLogger --version 1.1.0
          dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
          dotnet publish --configuration $buildConfiguration --output out
    - name: Test Report
      uses: zyborg/dotnet-tests-report@v1.0.0
      with:
        project_path: "**/*.trx"
        report_name: Unit_Tests
        report_title: My Project Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Build
      run: |
        DOCKER_BUILDKIT=1 docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from $REGISTRY_HOSTNAME/$SERVICE_NAME:$ENV-latest \
          -t $REGISTRY_HOSTNAME/$SERVICE_NAME:$ENV-$GITHUB_SHA \
          -t $REGISTRY_HOSTNAME/$SERVICE_NAME:$ENV-latest \
          -t $REGISTRY_HOSTNAME/$SERVICE_NAME:$ENV-$GITHUB_RUN_NUMBER \
          .
    
    
